# Generated by Django 3.0.1 on 2019-12-29 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0002_album_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='myfile',
        ),
    ]
